### PR TITLE
Modern

### PR DESCRIPTION
**Pull request by franciscop**
Working code and proposal for the first release of `translate`. It changes everything as explained in #20. Code is working with Google Translate and Yandex Translate API Keys and has a very modular core so people can make different engines as needed. Light memoizing added to avoid unnecessary requests.

Tests run with `npm test` and coverage is 95% now. Manual demos are provided for both `node.js` and the browsers, in `node.js` and `index.html` files respectively.

### CODE REVIEW

**Comment by Marak** [comment]
Is looks pretty good @franciscop!

I'm going to test a bit here but otherwise looks good to merge. I'll send you an email when I add you to package.

**Comment by franciscop** [comment]
Thank you @Marak! After the launch I will try to improve the documentation and tests.

**Comment by franciscop** [comment]
Hi @Marak, any update? It's been over 2 weeks and haven't heard back. I've launched https://serverjs.io/ in the meantime, but now I'd like to continue with this a bit.

**Comment by Marak** [comment]
You've had merge access for sometime I think.

**Comment by franciscop** [comment]
Sure, I thought that you wanted to test it for a bit before it was published. I will publish it soon.

**Pull request merged**
